### ISSUE TITLE
domcfghelper doesn't add property "xen,passthrough" to device which is hooked up to IOMMU but doesn't have IRQ

### ISSUE THREAD

**Issue by otyshchenko1** [xen-troops/xen-dom-cfg-helper#2]
The "xen,passthrough" property should be added for device nodes which are "bus master devices" (have "iommus" property) regardless has a particular device node IRQ or doesn't have.

**Comment by otyshchenko1** [comment]
ping...

**Comment by otyshchenko1** [comment]
The good example is

> 
		fcpvd0: fcp@fea27000 {
			compatible = "renesas,fcpv";
			reg = <0 0xfea27000 0 0x200>;
			clocks = <&cpg CPG_MOD 603>;
			power-domains = <&sysc R8A7795_PD_ALWAYS_ON>;

                        iommus = <&ipmmu_vi0 8>;	/* FCP-VD ch0 */
		};

>

**Comment by al1img** [comment]
Closed in e3fd60241d4c90d077e0ad25738cbf6c0032d438
