### ISSUE TITLE
"from pip.cmdoptions import src" doesn't work anymore

### ISSUE THREAD

**Issue by andr2000** [xen-troops/xen-dom-cfg-helper#4]
diff --git a/domcfghelper.py b/domcfghelper.py
index 0eb6256ee842..4438059658e1 100755
--- a/domcfghelper.py
+++ b/domcfghelper.py
@@ -3,7 +3,6 @@
 import argparse
 import re
 from pyfdt.pyfdt import *
-from pip.cmdoptions import src
 import ntpath
 import os
 import datetime

**Comment by al1img** [comment]
Looks like some redundant code. Could be removed.

**Comment by rshym** [comment]
Fixed by the https://github.com/xen-troops/xen-dom-cfg-helper/pull/5
